### ISSUE TITLE
Error en readkeyb

### ISSUE THREAD

**Issue by ddx2tb** [danirod-live/pascal2c#1]
Hay un error  que puede ocurrir en ciertas condiciones cuando se deja un espacio en la posición 80 o en múltiplos de 80. Este error se produce debido a que la función "readkeyb" elimina/ignora los espacios, lo que a su vez produce un error al parsear los tokens.

Esto solo sucedería en el "repl" debido a como se reserva el buffer del mismo.

Ejemplo (input):

**`if a < si_dejas_un_espacio_en_la_posicion_80_en_algunos_casos_fallara_thca then call_func`**

![image](https://github.com/danirod-live/pascal2c/assets/134472520/df49baed-0589-4f80-9bb8-82f27aec2e8e)

La función "readkeyb", la cual es responsable de ignorar los espacios y, por lo tanto, produce el error mencionado.

![image](https://github.com/danirod-live/pascal2c/assets/134472520/76b5c519-bd03-46cf-8713-7b73af7f15a7)

**Comment by danirod** [comment]
Vale, apunto para revisar en la próxima transmisión que haga de este repo.

¿Por qué leer del teclado en tiene que ser tan así 😄?

**Comment by ddx2tb** [comment]
Que seria de C sin su complejidad implícita para leer sin bugs la entrada del usuario.

**Comment by ddx2tb** [comment]
Estaré pendiente a la próxima transmisión para ver como lo solucionaras :face_in_clouds:

**Comment by danirod** [comment]
Corregido en fbb4ab0e4f7dc4697c310ad424fc3c9d548da997. Podría haberlo simplificado más, pero me da palo arreglar los bugs que salen.

**Comment by ddx2tb** [comment]
Me imagine que era algo como eso pero no tenia suficiente contexto para mandarte el PR y me perdí el directo pero vi la grabación 😝
